# Generated by Django 6.1.1 on 2026-09-20 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0002_assignment_course_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.course'),
        ),
    ]
