# Generated by Django 6.1.1 on 2026-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0003_alter_assignment_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.CharField(max_length=200),
        ),
    ]
