# Generated by Django 6.1.1 on 2026-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0004_alter_assignment_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
