# Generated by Django 6.1.1 on 2026-09-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0005_assignment_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.CASCADE, to='fullstack.course'),
            preserve_default=False,
        ),
    ]
